[package]
name = "cordis-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description = "Thin application host shell for cordis-loader."

[dependencies]
cordis-core.workspace = true
cordis-loader.workspace = true

[dev-dependencies]
async-trait.workspace = true
cordis-plugin-timer.workspace = true
schemars.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
